name: NetPlannedArea
definition: Total planned net area for the building  Used for programming the building.
dictionaryReference:
  dictionaryIdentifier: http://bsdd.buildingsmart.org
  dictionaryNamespace: PSet
  dictionaryWebUri: http://bsdd.buildingsmart.org/#concept/browse/0PFC40qSKHuO00025QrE$V
  dictionaryApiUri: http://bsdd.buildingsmart.org/api/4.0/IfdConcept/0PFC40qSKHuO00025QrE$V
  ifdGuid: 0PFC40qSKHuO00025QrE$V
  legacyGuid: 193cc100d1c511e1800000215ad4efdf
  legacyGuids:
  - 0PFC40qSKHuO00025QrE$V
  - 2bvty0qSKHuO00025QrE$V
  - 06v7Q0qWaHuO00025QrE$V
  - 0uJyku3QH6VfEOZJ6gIkEg
  legacyGuidAsIfcGlobalId: 0PFC40qSKHuO00025QrE$V
localizations:
- language: de-DE
  name: 'Nettofläche nach Raumprogramm'
  definition: 'Geforderte Nettofläche des Gebäudes laut Raumprogramm.'
- language: en
  name: 'Net Planned Area'
  definition: ''
- language: fr-FR
  name: 'Surface programmée nette'
  definition: 'Surface programmée nette totale du bâtiment. Telle que définie lors de la programmation.'
- language: ja-JP
  name: '計画ネット面積'
  definition: '計画されたネット面積。建物計画に際に使用。（通常は、柱型等を抜いた面積となる）'
- language: en-GB
  name: ''
  definition: ''
- language: es-ES
  name: ''
  definition: ''
- language: ru-RU
  name: ''
  definition: ''
typePropertySingleValue:
  dataType: IfcAreaMeasure
  measureType: ''
  unitType: USERDEFINED
status:
  versionNumber: 4
  dateOfVersion: 2018-01-01T00:00:00.0000000
  revisionNumber: 2
  dateOfRevision: 2018-01-01T00:00:00.0000000
  status: Active
  dateOfCreation: 2018-01-01T00:00:00.0000000
  dateOfActivation: 2018-01-01T00:00:00.0000000
  dateOfLastChange: 2018-01-01T00:00:00.0000000
  languageOfCreator: en-EN
