name: ProductDescription
definition: A textual description of the products that require the work.
dictionaryReference:
  dictionaryIdentifier: http://bsdd.buildingsmart.org
  dictionaryNamespace: PSet
  dictionaryWebUri: http://bsdd.buildingsmart.org/#concept/browse/3_DtI0qVSHuO00025QrE$V
  dictionaryApiUri: http://bsdd.buildingsmart.org/api/4.0/IfdConcept/3_DtI0qVSHuO00025QrE$V
  ifdGuid: 3_DtI0qVSHuO00025QrE$V
  legacyGuid: fe377480d1f711e1800000215ad4efdf
  legacyGuids:
  - 3_DtI0qVSHuO00025QrE$V
  - 1Jlr60qVSHuO00025QrE$V
  legacyGuidAsIfcGlobalId: 3_DtI0qVSHuO00025QrE$V
localizations:
- language: en
  name: 'Product Description'
  definition: ''
- language: de-DE
  name: ''
  definition: ''
- language: en-GB
  name: ''
  definition: ''
- language: es-ES
  name: ''
  definition: ''
- language: fr-FR
  name: ''
  definition: ''
- language: ja-JP
  name: ''
  definition: ''
- language: ru-RU
  name: ''
  definition: ''
typePropertySingleValue:
  dataType: IfcText
  measureType: ''
  unitType: USERDEFINED
status:
  versionNumber: 4
  dateOfVersion: 2018-01-01T00:00:00.0000000
  revisionNumber: 2
  dateOfRevision: 2018-01-01T00:00:00.0000000
  status: Active
  dateOfCreation: 2018-01-01T00:00:00.0000000
  dateOfActivation: 2018-01-01T00:00:00.0000000
  dateOfLastChange: 2018-01-01T00:00:00.0000000
  languageOfCreator: en-EN
