name: AirFlowConfiguration
definition: Air flow configuration type of cooled beam.
dictionaryReference:
  dictionaryIdentifier: http://bsdd.buildingsmart.org
  dictionaryNamespace: PSet
  dictionaryWebUri: http://bsdd.buildingsmart.org/#concept/browse/1yVo40qSuHuO00025QrE$V
  dictionaryApiUri: http://bsdd.buildingsmart.org/api/4.0/IfdConcept/1yVo40qSuHuO00025QrE$V
  ifdGuid: 1yVo40qSuHuO00025QrE$V
  legacyGuid: 7c7f2100d1ce11e1800000215ad4efdf
  legacyGuids:
  - 1yVo40qSuHuO00025QrE$V
  legacyGuidAsIfcGlobalId: 1yVo40qSuHuO00025QrE$V
localizations:
- language: en
  name: 'Air Flow Configuration'
  definition: ''
- language: de-DE
  name: ''
  definition: ''
- language: en-GB
  name: ''
  definition: ''
- language: es-ES
  name: ''
  definition: ''
- language: fr-FR
  name: ''
  definition: ''
- language: ja-JP
  name: ''
  definition: ''
- language: ru-RU
  name: ''
  definition: ''
typePropertyEnumeratedValue:
  constantValues:
  - name: BIDIRECTIONAL
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: UNIDIRECTIONALRIGHT
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: UNIDIRECTIONALLEFT
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: OTHER
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: NOTKNOWN
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: UNSET
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
status:
  versionNumber: 4
  dateOfVersion: 2018-01-01T00:00:00.0000000
  revisionNumber: 2
  dateOfRevision: 2018-01-01T00:00:00.0000000
  status: Active
  dateOfCreation: 2018-01-01T00:00:00.0000000
  dateOfActivation: 2018-01-01T00:00:00.0000000
  dateOfLastChange: 2018-01-01T00:00:00.0000000
  languageOfCreator: en-EN
