name: Application
definition: The application of the unitary control element.
dictionaryReference:
  dictionaryIdentifier: http://bsdd.buildingsmart.org
  dictionaryNamespace: PSet
  dictionaryWebUri: http://bsdd.buildingsmart.org/#concept/browse/1SFFLf$JXEhOlwpLeQKQeS
  dictionaryApiUri: http://bsdd.buildingsmart.org/api/4.0/IfdConcept/1SFFLf$JXEhOlwpLeQKQeS
  ifdGuid: 1SFFLf$JXEhOlwpLeQKQeS
  legacyGuid: a214298bc8bc4c2d91e02d20124d29f8
  legacyGuids:
  - 2Y52cBoBnCBP7WBI0IJIdu
  legacyGuidAsIfcGlobalId: 2Y52cBoBnCBP7WBI0IJIdu
localizations:
- language: en
  name: 'Application'
  definition: ''
- language: de-DE
  name: ''
  definition: ''
- language: en-GB
  name: ''
  definition: ''
- language: es-ES
  name: ''
  definition: ''
- language: fr-FR
  name: ''
  definition: ''
- language: ja-JP
  name: ''
  definition: ''
- language: ru-RU
  name: ''
  definition: ''
typePropertyEnumeratedValue:
  constantValues:
  - name: LIFTPOSITIONINDICATOR
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: LIFTHALLLANTERN
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: LIFTARRIVALGONG
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: LIFTCARDIRECTIONLANTERN
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: LIFTFIRESYSTEMSPORT
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: LIFTVOICEANNOUNCER
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: OTHER
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: NOTKNOWN
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: UNSET
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
status:
  versionNumber: 4
  dateOfVersion: 2018-01-01T00:00:00.0000000
  revisionNumber: 2
  dateOfRevision: 2018-01-01T00:00:00.0000000
  status: Active
  dateOfCreation: 2018-01-01T00:00:00.0000000
  dateOfActivation: 2018-01-01T00:00:00.0000000
  dateOfLastChange: 2018-01-01T00:00:00.0000000
  languageOfCreator: en-EN
