name: ApplicationOfFan
definition: 'The functional application of the fan.SupplyAir: Supply air fan. ReturnAir: Return air fan. ExhaustAir: Exhaust air fan. Other: Other type of application not defined above.'
dictionaryReference:
  dictionaryIdentifier: http://bsdd.buildingsmart.org
  dictionaryNamespace: PSet
  dictionaryWebUri: http://bsdd.buildingsmart.org/#concept/browse/3Fhvw0qUCHuO00025QrE$V
  dictionaryApiUri: http://bsdd.buildingsmart.org/api/4.0/IfdConcept/3Fhvw0qUCHuO00025QrE$V
  ifdGuid: 3Fhvw0qUCHuO00025QrE$V
  legacyGuid: cfaf9e80d1e311e1800000215ad4efdf
  legacyGuids:
  - 3Fhvw0qUCHuO00025QrE$V
  legacyGuidAsIfcGlobalId: 3Fhvw0qUCHuO00025QrE$V
localizations:
- language: en
  name: 'Application Of Fan'
  definition: ''
- language: ja-JP
  name: 'Fan用途'
  definition: 'Fanの系統SUPPLYAIR, RETURNAIR, EXHAUSTAIR, COOLINGTOWER, OTHER'
- language: de-DE
  name: ''
  definition: ''
- language: en-GB
  name: ''
  definition: ''
- language: es-ES
  name: ''
  definition: ''
- language: fr-FR
  name: ''
  definition: ''
- language: ru-RU
  name: ''
  definition: ''
typePropertyEnumeratedValue:
  constantValues:
  - name: SUPPLYAIR
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: RETURNAIR
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: EXHAUSTAIR
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: COOLINGTOWER
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: OTHER
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: NOTKNOWN
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
  - name: UNSET
    definition: ''
    ifdGuid: ''
    localizations:
    - language: de-DE
      name: ''
      definition: ''
    - language: en-GB
      name: ''
      definition: ''
    - language: es-ES
      name: ''
      definition: ''
    - language: fr-FR
      name: ''
      definition: ''
    - language: ja-JP
      name: ''
      definition: ''
    - language: ru-RU
      name: ''
      definition: ''
status:
  versionNumber: 4
  dateOfVersion: 2018-01-01T00:00:00.0000000
  revisionNumber: 2
  dateOfRevision: 2018-01-01T00:00:00.0000000
  status: Active
  dateOfCreation: 2018-01-01T00:00:00.0000000
  dateOfActivation: 2018-01-01T00:00:00.0000000
  dateOfLastChange: 2018-01-01T00:00:00.0000000
  languageOfCreator: en-EN
