name: OutdoorEnvironment
definition: Adjustment of the service life resulting from the effect of the outdoor environment (where appropriate)
dictionaryReference:
  dictionaryIdentifier: http://bsdd.buildingsmart.org
  dictionaryNamespace: PSet
  dictionaryWebUri: http://bsdd.buildingsmart.org/#concept/browse/3KTA7uHAv75glWgT0ElH8G
  dictionaryApiUri: http://bsdd.buildingsmart.org/api/4.0/IfdConcept/3KTA7uHAv75glWgT0ElH8G
  ifdGuid: 3KTA7uHAv75glWgT0ElH8G
  legacyGuid: 9988ab22befe45c9ab3c94972c61bd90
  legacyGuids:
  - 2PYAiYllv5oQiyb9SiORsG
  legacyGuidAsIfcGlobalId: 2PYAiYllv5oQiyb9SiORsG
localizations:
- language: en
  name: 'Outdoor Environment'
  definition: ''
- language: de-DE
  name: ''
  definition: ''
- language: en-GB
  name: ''
  definition: ''
- language: es-ES
  name: ''
  definition: ''
- language: fr-FR
  name: ''
  definition: ''
- language: ja-JP
  name: ''
  definition: ''
- language: ru-RU
  name: ''
  definition: ''
typePropertyBoundedValue:
  unitType: USERDEFINED
  LowerBoundValue: ''
  UpperBoundValue: ''
  typeName: TypePropertyBoundedValue
status:
  versionNumber: 4
  dateOfVersion: 2018-01-01T00:00:00.0000000
  revisionNumber: 2
  dateOfRevision: 2018-01-01T00:00:00.0000000
  status: Active
  dateOfCreation: 2018-01-01T00:00:00.0000000
  dateOfActivation: 2018-01-01T00:00:00.0000000
  dateOfLastChange: 2018-01-01T00:00:00.0000000
  languageOfCreator: en-EN
